name: Website Build CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          path: website

      - name: Set ENV vars
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
          MAX_AGE: ${{ secrets.MAX_AGE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo $BUCKET_NAME      

      - name: Top level folders in website repo
        run: ls website
      
      - name: Get HUGO container
        run: docker pull khsiller/hugo-builder:0.79.0
      
      - name: Build webpages
        run: |
          docker run -v $(pwd)/website:/website -w /website khsiller/hugo-builder:0.79.0 hugo --minify -v --ignoreCache
          ls website/public
        
      - name: Upload to S3 and invalidate cache
        run: |
          aws s3 sync website/public s3://$BUCKET_NAME --region=us-east-1 --cache-control public,max-age=$MAX_AGE,s-maxage=$MAX_AGE --expires="$EXPIRES" --metadata generator=$HUGO --delete
          aws s3 cp website/public s3://$BUCKET_NAME --metadata-directive REPLACE --exclude "*" --include "*.jpg" --include "*.gif" --include "*.png" --recursive --cache-control max-age=604800,s-maxage=604800
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*";
















