name: Website Build CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: staging
          path: website

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls
      
      - name: Get HUGO container
        run: docker pull khsiller/hugo-builder:0.79.0
      
      - name: Run HUGO container
        run: docker run -v $(pwd):/website -w /website khsiller/hugo-builder:0.79.0 hugo version
      
      # Runs a set of commands using the runners shell
      - name: 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
















