name: Website Build CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          path: website

      # Runs a single command using the runners shell
      - name: Top level folders in website repo
        run: ls website
      
      - name: Get HUGO container
        run: docker pull khsiller/hugo-builder:0.79.0
      
      - name: Build webpages
        run: |
          docker run -v $(pwd)/website:/website -w /website khsiller/hugo-builder:0.79.0 hugo
          ls website/public
        
      - name: Upload to S3 and invalidate cache
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
















